version: '3.9'
services:
  db:
    image: 'postgres:15.2-alpine'
    restart: always
    container_name: db_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=persons_db
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d persons_db'" ]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - pg_data:/var/lib/postgresql/data
  app:
    image: 'tc-sandbox-app:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tc_sandbox
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
volumes:
  pg_data:
    driver: local